### ISSUE TITLE
MOVES cannot write to database

### ISSUE THREAD

**Issue by Hanisek** [USEPA/EPA_MOVES_Model#69]
I am running MOVES4 on RHEL 7, and I have the following error messages:

3/15/24, 8:46 PM DEBUG: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\xE2\x80\xAFPM ...' for column `atlanta_2020_7_75_75`.`moveserror`.`errorMessage` at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3595)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1990)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2151)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2625)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2119)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
	at gov.epa.otaq.moves.common.SQLRunner.execute(SQLRunner.java:273)
	at gov.epa.otaq.moves.master.framework.MOVESEngine.logRunError(MOVESEngine.java:1673)
	at gov.epa.otaq.moves.master.framework.MOVESEngine.handleLog(MOVESEngine.java:1574)
	at gov.epa.otaq.moves.common.Logger.log(Logger.java:113)
	at gov.epa.otaq.moves.master.framework.AggregationSQLGenerator.validateAggregation(AggregationSQLGenerator.java:591)
	at gov.epa.otaq.moves.master.framework.AggregationSQLGenerator.generateReportSQL(AggregationSQLGenerator.java:441)
	at gov.epa.otaq.moves.master.framework.ExecutionRunSpec.initializeBeforeIteration(ExecutionRunSpec.java:357)
	at gov.epa.otaq.moves.master.framework.MasterLoop.threadIterationGo(MasterLoop.java:412)
	at gov.epa.otaq.moves.master.framework.MasterLoop.calcHowManyOutboundBundlesWillBeCreated(MasterLoop.java:1019)
	at gov.epa.otaq.moves.master.framework.MasterLoop.startupInThread(MasterLoop.java:297)
	at gov.epa.otaq.moves.common.MOVESThread.run(MOVESThread.java:190)

I grant all privileges to moves@localhost and moves@127.0.0.1, and set all character sets (in my.cnf and for all databases) to be utf8mb4.  Is this a character set issue, or there is something else?

**Comment by Hanisek** [comment]
BTW here is my.cnf file that I am using:

[mysqld]
datadir=/tmp/11121042/MariaDB/lib/mysql
socket=/tmp/11121042/MariaDB/lib/mysql/mysql.sock



default-storage-engine=MyISAM
secure-file-priv=''
sql_mode=STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
lower_case_table_names=1
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
init-connect='SET NAMES utf8'


[mysqld_safe]
log-error=/tmp/11121042/MariaDB/log/mariadb/mariadb.log
pid-file=/tmp/11121042/MariaDB/run/mariadb/mariadb.pid

**Comment by danielbizercox** [comment]
It looks like you are probably using JDK21 to compile MOVES, which includes a special narrow nonbreaking space in the default timestamp. Even though your configuration file specifies utf8mb4 as the default character set, MOVES4 creates output databases using the latin1 character set. In most cases, this does not cause a problem--however, when MOVES tries to create an entry in the `moveserror` table, it includes the timestamp of the error, which generates this error message.

Because of this issue and a few other warning messages when using JDK21, we recommend sticking with JDK17 for MOVES4.

However, we are aware of this issue and the next major release of MOVES will be fully compatible with JDK21.

**Comment by Hanisek** [comment]
> It looks like you are probably using JDK21 to compile MOVES, which includes a special narrow nonbreaking space in the default timestamp. Even though your configuration file specifies utf8mb4 as the default character set, MOVES4 creates output databases using the latin1 character set. In most cases, this does not cause a problem--however, when MOVES tries to create an entry in the `moveserror` table, it includes the timestamp of the error, which generates this error message.
> 
> Because of this issue and a few other warning messages when using JDK21, we recommend sticking with JDK17 for MOVES4.
> 
> However, we are aware of this issue and the next major release of MOVES will be fully compatible with JDK21.

Thank you so much for your help, Daniel!  MOVES runs fine on my RHEL with GUI locally.
Now I managed to get MOVES launched on the supercomputing cluster (which has no GUI), but I cannot import any data using commandline and xml (they worked fine locally). I got the following errors:

3/21/24, 8:31 PM DEBUG: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at gov.epa.otaq.moves.master.framework.importers.ImporterInstantiator.createByClassName(ImporterInstantiator.java:213)
        at gov.epa.otaq.moves.master.framework.importers.ImporterInstantiator.createByXMLNodeType(ImporterInstantiator.java:195)
        at gov.epa.otaq.moves.master.framework.importers.ImporterManager.fromXML(ImporterManager.java:985)
        at gov.epa.otaq.moves.master.framework.importers.ImporterManager.fromXML(ImporterManager.java:909)
        at gov.epa.otaq.moves.master.framework.MOVESAPI.runBatch(MOVESAPI.java:651)
        at gov.epa.otaq.moves.master.framework.MOVESAPI.runApplication(MOVESAPI.java:308)
        at gov.epa.otaq.moves.master.commandline.MOVESCommandLine.main(MOVESCommandLine.java:32)
Caused by: java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:101)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:60)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:36)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
        at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:224)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:40)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:599)
        at java.desktop/sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2206)
        at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1100)
        at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:446)
        at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:153)
        at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1566)
        at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:593)
        at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:635)
        at java.desktop/javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1412)
        at java.desktop/javax.swing.UIManager.initialize(UIManager.java:1525)
        at java.desktop/javax.swing.UIManager.maybeInitialize(UIManager.java:1491)
        at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1063)
        at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:129)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:89)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:112)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:120)
        at gov.epa.otaq.moves.master.framework.importers.TableFileLinkagePart.<init>(TableFileLinkagePart.java:124)
        at gov.epa.otaq.moves.master.implementation.importers.LinkImporter.<init>(LinkImporter.java:141)
        ... 12 more

null
3/21/24, 8:31 PM ERROR: ImporterInstantiator is unable to instantiate gov.epa.otaq.moves.master.implementation.importers.LinkImporter

Is this something related to headless mode?

Thanks in advance for your help!

**Comment by Hanisek** [comment]
> > It looks like you are probably using JDK21 to compile MOVES, which includes a special narrow nonbreaking space in the default timestamp. Even though your configuration file specifies utf8mb4 as the default character set, MOVES4 creates output databases using the latin1 character set. In most cases, this does not cause a problem--however, when MOVES tries to create an entry in the `moveserror` table, it includes the timestamp of the error, which generates this error message.
> > Because of this issue and a few other warning messages when using JDK21, we recommend sticking with JDK17 for MOVES4.
> > However, we are aware of this issue and the next major release of MOVES will be fully compatible with JDK21.
> 
> Thank you so much for your help, Daniel! MOVES runs fine on my RHEL with GUI locally. Now I managed to get MOVES launched on the supercomputing cluster (which has no GUI), but I cannot import any data using commandline and xml (they worked fine locally). I got the following errors:
> 
> 3/21/24, 8:31 PM DEBUG: java.lang.reflect.InvocationTargetException at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) at gov.epa.otaq.moves.master.framework.importers.ImporterInstantiator.createByClassName(ImporterInstantiator.java:213) at gov.epa.otaq.moves.master.framework.importers.ImporterInstantiator.createByXMLNodeType(ImporterInstantiator.java:195) at gov.epa.otaq.moves.master.framework.importers.ImporterManager.fromXML(ImporterManager.java:985) at gov.epa.otaq.moves.master.framework.importers.ImporterManager.fromXML(ImporterManager.java:909) at gov.epa.otaq.moves.master.framework.MOVESAPI.runBatch(MOVESAPI.java:651) at gov.epa.otaq.moves.master.framework.MOVESAPI.runApplication(MOVESAPI.java:308) at gov.epa.otaq.moves.master.commandline.MOVESCommandLine.main(MOVESCommandLine.java:32) Caused by: java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable. at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method) at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:101) at java.base/java.security.AccessController.doPrivileged(AccessController.java:318) at java.desktop/sun.awt.X11GraphicsEnvironment.(X11GraphicsEnvironment.java:60) at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:36) at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93) at java.desktop/java.awt.GraphicsEnvironment$LocalGE.(GraphicsEnvironment.java:84) at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106) at java.desktop/sun.awt.X11.XToolkit.(XToolkit.java:224) at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:40) at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:599) at java.desktop/sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2206) at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1100) at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:446) at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:153) at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1566) at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:593) at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:635) at java.desktop/javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1412) at java.desktop/javax.swing.UIManager.initialize(UIManager.java:1525) at java.desktop/javax.swing.UIManager.maybeInitialize(UIManager.java:1491) at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1063) at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:129) at java.desktop/javax.swing.JPanel.(JPanel.java:89) at java.desktop/javax.swing.JPanel.(JPanel.java:112) at java.desktop/javax.swing.JPanel.(JPanel.java:120) at gov.epa.otaq.moves.master.framework.importers.TableFileLinkagePart.(TableFileLinkagePart.java:124) at gov.epa.otaq.moves.master.implementation.importers.LinkImporter.(LinkImporter.java:141) ... 12 more
> 
> null 3/21/24, 8:31 PM ERROR: ImporterInstantiator is unable to instantiate gov.epa.otaq.moves.master.implementation.importers.LinkImporter
> 
> Is this something related to headless mode?
> 
> Thanks in advance for your help!

Nevermind.  I added -Djava.awt.headless=true to the java command, and it works!!  Thanks again, Daniel!
